version: '2'

services:
  web:
    image: nginx:alpine
    volumes:
      - "./docker/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./:/var/www/html"
    ports:
      - "80:80"

  php:
    build: "."
    volumes:
      - "./:/var/www/html"
      - "./docker/php.ini:/usr/local/etc/php/conf.d/winsite.ini"

  db:
    image: mysql:5.7
    volumes:
      - "./data:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: montenegro
      MYSQL_USER: montenegro
      MYSQL_PASSWORD: montenegro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=montenegro
      - PMA_PASSWORD=montenegro
    restart: always
    ports:
      - "8080:80"
